on:
  push:
    branches: [develop]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build Flatpak
      uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
      with:
        bundle: live.senkins.SeventhHeavenWrapper.flatpak
        manifest-path: live.senkins.SeventhHeavenWrapper.yml
        cache-key: flatpak-builder-${{ github.sha }}
